<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/cgi-bin/koha/mainpage.pl">Home</a></li>
    <li class="breadcrumb-item"><a href="/cgi-bin/koha/plugins/plugins-home.pl">Plugins</a></li>
    <li class="breadcrumb-item active"><a href="#">LMSEventManagement</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="#">Loading...</a></li>
  </ol>
</nav>