INSERT INTO koha_plugin_com_lmscloud_eventmanagement_event_types (
        id,
        name,
        branch,
        target_group,
        max_age,
        min_age,
        open_registration,
        max_participants,
        fee,
        description
    )
VALUES (
        'LESUNG',
        'Lesung',
        'CPL',
        'ERWACHSENE',
        255, 
        0,
        1,
        50,
        8,
        NULL
    ),
    (
        'MUSIK',
        'Musik',
        'TPL',
        'ERWACHSENE',
        255,
        0,
        1,
        100,
        19,
        NULL
    ),
    (
        'THEATER',
        'Theater',
        'UPL',
        'ERWACHSENE',
        255,
        0,
        1,
        100,
        25,
        NULL
    ),
    (
        'SONST',
        'Sonstiges',
        'SPL',
        'ERWACHSENE',
        255,
        0,
        1,
        10,
        0,
        NULL
    );